const heroDisplayNames = {
  antimage: "Anti-Mage",
  axe: "Axe",
  bane: "Bane",
  bloodseeker: "Bloodseeker",
  crystal_maiden: "Crystal Maiden",
  drow_ranger: "Drow Ranger",
  earthshaker: "Earthshaker",
  juggernaut: "Juggernaut",
  mirana: "Mirana",
  morphling: "Morphling",
  shadow_fiend: "Shadow Fiend",
  phantom_lancer: "Phantom Lancer",
  puck: "Puck",
  pudge: "Pudge",
  razor: "Razor",
  sand_king: "Sand King",
  storm_spirit: "Storm Spirit",
  sven: "Sven",
  tiny: "Tiny",
  vengeful_spirit: "Vengeful Spirit",
  windrunner: "Windranger",
  zeus: "Zeus",
  kunkka: "Kunkka",
  lina: "Lina",
  lion: "Lion",
  shadow_shaman: "Shadow Shaman",
  slardar: "Slardar",
  tidehunter: "Tidehunter",
  witch_doctor: "Witch Doctor",
  riki: "Riki",
  enigma: "Enigma",
  tinker: "Tinker",
  sniper: "Sniper",
  necrolyte: "Necrophos",
  warlock: "Warlock",
  beastmaster: "Beastmaster",
  queenofpain: "Queen of Pain",
  venomancer: "Venomancer",
  faceless_void: "Faceless Void",
  skeleton_king: "Wraith King",
  death_prophet: "Death Prophet",
  phantom_assassin: "Phantom Assassin",
  pugna: "Pugna",
  templar_assassin: "Templar Assassin",
  viper: "Viper",
  luna: "Luna",
  dragon_knight: "Dragon Knight",
  dazzle: "Dazzle",
  clockwerk: "Clockwerk",
  leshrac: "Leshrac",
  furion: "Natures Prophet",
  lifestealer: "Lifestealer",
  dark_seer: "Dark Seer",
  clinkz: "Clinkz",
  omniknight: "Omniknight",
  enchantress: "Enchantress",
  huskar: "Huskar",
  night_stalker: "Night Stalker",
  broodmother: "Broodmother",
  bounty_hunter: "Bounty Hunter",
  weaver: "Weaver",
  jakiro: "Jakiro",
  batrider: "Batrider",
  chen: "Chen",
  spectre: "Spectre",
  doom_bringer: "Doom",
  ancient_apparition: "Ancient Apparition",
  ursa: "Ursa",
  spirit_breaker: "Spirit Breaker",
  gyrocopter: "Gyrocopter",
  alchemist: "Alchemist",
  invoker: "Invoker",
  silencer: "Silencer",
  outworld_destroyer: "Outworld Devourer",
  lycan: "Lycan",
  brewmaster: "Brewmaster",
  shadow_demon: "Shadow Demon",
  lone_druid: "Lone Druid",
  chaos_knight: "Chaos Knight",
  meepo: "Meepo",
  treant: "Treant Protector",
  ogre_magi: "Ogre Magi",
  undying: "Undying",
  rubick: "Rubick",
  disruptor: "Disruptor",
  nyx_assassin: "Nyx Assassin",
  naga_siren: "Naga Siren",
  keeper_of_the_light: "Keeper of the Light",
  wisp: "Io",
  visage: "Visage",
  slark: "Slark",
  medusa: "Medusa",
  troll_warlord: "Troll Warlord",
  centaur: "Centaur Warrunner",
  magnataur: "Magnus",
  shredder: "Timbersaw",
  bristleback: "Bristleback",
  tusk: "Tusk",
  skywrath_mage: "Skywrath Mage",
  abaddon: "Abaddon",
  elder_titan: "Elder Titan",
  legion_commander: "Legion Commander",
  techies: "Techies",
  ember_spirit: "Ember Spirit",
  earth_spirit: "Earth Spirit",
  underlord: "Underlord",
  terrorblade: "Terrorblade",
  phoenix: "Phoenix",
  oracle: "Oracle",
  winter_wyvern: "Winter Wyvern",
  arc_warden: "Arc Warden",
  monkey_king: "Monkey King",
  pangolier: "Pangolier",
  dark_willow: "Dark Willow",
  grimstroke: "Grimstroke",
  hoodwink: "Hoodwink",
  void_spirit: "Void Spirit",
  snapfire: "Snapfire",
  mars: "Mars",
  dawnbreaker: "Dawnbreaker",
  marci: "Marci",
  primal_beast: "Primal Beast",
  muerta: "Muerta",
  ringmaster: "Ringmaster",
  techies_2: "Techies 2",
  abyssal_underlord: "Underlord",
};

export default heroDisplayNames;
